### ISSUE TITLE
Create option to allow categories to populate

### ISSUE THREAD

**Issue by slocker3** [happyprime/latest-custom-posts#33]
**Currently:**
The LCP doesn't have a path for populating categories (or tags) in the output. The taxonomy slugs are, however, populated as classes.

**Proposed change:**
Allow the output of categories in LCP. I think this should be a toggle option in the admin that is defaulted to not populate.

**Comment by slocker3** [comment]
I think it is fine to only output WordPress's default category taxonomy to start. It might be interesting to see what a path looks like for populating WordPress's default tags, and then custom taxonomies.

**Comment by webelaine** [comment]
It looks like Core may have changed the `post_class()` function to include categories and custom taxonomies. Testing on SAFMC, I am seeing categories on the CAB items such as `cab-category-uncategorized` and `cab-fish_species_connect-snapper-red`. @slocker3 would you care to take a look and check whether what's already there is what you had intended in this issue? :)
