### ISSUE TITLE
Option to display a thumbnail or other sized image

### ISSUE THREAD

**Issue by jeremyfelt** [happyprime/latest-custom-posts#4]
It's possible that this isn't necessary with some of the upstream changes from the latest posts block in core, but we can do some digging.

**Comment by philcable** [comment]
Just noting that https://github.com/happyprime/latest-custom-posts/pull/11 introduces a custom endpoint that returns a limited set of data per post, so if it gets merged into master, that data will need to be extended when this feature is added :).
