### ISSUE TITLE
Improve spacing within category/tag selection box

### ISSUE THREAD

**Issue by jeremyfelt** [happyprime/latest-custom-posts#54]
In the current interface, I think there is room for a bit of padding above the top category. In a future interface, we may need to do a search as you type to help with long lists.

<img width="276" alt="Screen Shot 2021-08-19 at 11 19 32 AM" src="https://user-images.githubusercontent.com/286171/130123181-94139713-7c08-4db4-84c2-8c90dd1ce77a.png">

**Comment by philcable** [comment]
Fixed in #57.
