### ISSUE TITLE
Improve "Taxonomy Settings" area

### ISSUE THREAD

**Issue by jeremyfelt** [happyprime/latest-custom-posts#55]
The interface jumps around quite a bit when more than one taxonomy filter is added. I think we can probably always include the "Taxonomy Settings" heading and then space things so that they are only appended to the list of filters in a way that existing UI does not flash.

![taxonomy-settings](https://user-images.githubusercontent.com/286171/130123483-f2db7f98-838e-4611-8343-387af1535db9.gif)

**Comment by philcable** [comment]
We probably have an opportunity for further improvements, but I think #57 clears up the worst of the issues, so closing for now.
