### ISSUE TITLE
Adding classes for when elements are toggled on

### ISSUE THREAD

**Issue by slocker3** [happyprime/latest-custom-posts#56]
Can we add `.cab-has-post-excerpt` and `.cab-has-post-date` classes to either the li when those are toggled on? It does currently add `.cab-has-post-thumbnail` when the image toggle is selected.

This is helpful for adjusting the  layout of content depending on what is selected.

**Comment by philcable** [comment]
Fixed in #57. The PR description contains notes about this - including those in the README would be a good idea 🙂.
